-- MySQL Script generated by MySQL Workbench
-- Thu Jun  2 02:43:18 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbsistRel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbsistRel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbsistRel` DEFAULT CHARACTER SET utf8 ;
USE `dbsistRel` ;

-- -----------------------------------------------------
-- Table `dbsistRel`.`Lotes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistRel`.`Lotes` (
  `idLote` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`idLote`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistRel`.`Casas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistRel`.`Casas` (
  `idCasa` INT NOT NULL AUTO_INCREMENT,
  `idLote` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`idCasa`),
  CONSTRAINT `fk_Casas_Lotes1`
    FOREIGN KEY (`idLote`)
    REFERENCES `dbsistRel`.`Lotes` (`idLote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistRel`.`hogares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistRel`.`hogares` (
  `idhogar` INT NOT NULL AUTO_INCREMENT,
  `idCasa` INT NOT NULL,
  PRIMARY KEY (`idhogar`),
  CONSTRAINT `fk_hogares_Casas1`
    FOREIGN KEY (`idCasa`)
    REFERENCES `dbsistRel`.`Casas` (`idCasa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistRel`.`Relevamientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistRel`.`Relevamientos` (
  `idRelevamiento` INT NOT NULL AUTO_INCREMENT,
  `fechaDesde` DATE NULL,
  `idhogar` INT NOT NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`idRelevamiento`),
  CONSTRAINT `fk_Relevamientos_hogares1`
    FOREIGN KEY (`idhogar`)
    REFERENCES `dbsistRel`.`hogares` (`idhogar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistRel`.`Manzanas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistRel`.`Manzanas` (
  `idManzana` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idManzana`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistRel`.`Barrios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistRel`.`Barrios` (
  `idBarrio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`idBarrio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistRel`.`Barrio_Manzanas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistRel`.`Barrio_Manzanas` (
  `idBarrio_Manzanas` INT NOT NULL AUTO_INCREMENT,
  `idBarrio` INT NOT NULL,
  `idManzan` INT NOT NULL,
  PRIMARY KEY (`idBarrio_Manzanas`),
  CONSTRAINT `fk_Barrio_Manzanas_Manzanas1`
    FOREIGN KEY (`idManzan`)
    REFERENCES `dbsistRel`.`Manzanas` (`idManzana`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Barrio_Manzanas_Barrios1`
    FOREIGN KEY (`idBarrio`)
    REFERENCES `dbsistRel`.`Barrios` (`idBarrio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistRel`.`Manzana_Lotes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistRel`.`Manzana_Lotes` (
  `idManzana_Lote` INT NOT NULL AUTO_INCREMENT,
  `Manzanas_idManzana` INT NOT NULL,
  `idLote` INT NOT NULL,
  PRIMARY KEY (`idManzana_Lote`),
  CONSTRAINT `fk_Manzana_Lotes_Manzanas1`
    FOREIGN KEY (`Manzanas_idManzana`)
    REFERENCES `dbsistRel`.`Manzanas` (`idManzana`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Manzana_Lotes_Lotes1`
    FOREIGN KEY (`idLote`)
    REFERENCES `dbsistRel`.`Lotes` (`idLote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistRel`.`Telefonos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistRel`.`Telefonos` (
  `idTelefono` INT NOT NULL AUTO_INCREMENT,
  `tipoTelefono` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `idCasa` INT NOT NULL,
  PRIMARY KEY (`idTelefono`),
  CONSTRAINT `fk_Telefonos_Casas1`
    FOREIGN KEY (`idCasa`)
    REFERENCES `dbsistRel`.`Casas` (`idCasa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistRel`.`Personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistRel`.`Personas` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `vinculo` VARCHAR(45) NULL,
  `nombres` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `dni` VARCHAR(45) NULL,
  `fechaNacimiento` DATE NULL,
  `ocupacion` VARCHAR(45) NULL,
  `hogares_idhogar` INT NOT NULL,
  PRIMARY KEY (`idPersona`),
  CONSTRAINT `fk_Personas_hogares1`
    FOREIGN KEY (`hogares_idhogar`)
    REFERENCES `dbsistRel`.`hogares` (`idhogar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistRel`.`Patologias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistRel`.`Patologias` (
  `idPatologia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL,
  PRIMARY KEY (`idPatologia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistRel`.`Discapacidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistRel`.`Discapacidades` (
  `idDiscapacidade` INT NOT NULL AUTO_INCREMENT,
  `discapacidad` TINYINT NULL,
  `cud` TINYINT NULL,
  `idPersona` INT NOT NULL,
  `idPatologia` INT NOT NULL,
  PRIMARY KEY (`idDiscapacidade`),
  CONSTRAINT `fk_Discapacidades_Personas1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `dbsistRel`.`Personas` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Discapacidades_Patologias1`
    FOREIGN KEY (`idPatologia`)
    REFERENCES `dbsistRel`.`Patologias` (`idPatologia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistRel`.`Niveles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistRel`.`Niveles` (
  `idNivel` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idNivel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistRel`.`Escolaridades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistRel`.`Escolaridades` (
  `idEscolaridade` INT NOT NULL,
  `escolaridad` TINYINT NULL,
  `idNivel` INT NOT NULL,
  `idPersona` INT NOT NULL,
  PRIMARY KEY (`idEscolaridade`),
  CONSTRAINT `fk_Escolaridades_Niveles1`
    FOREIGN KEY (`idNivel`)
    REFERENCES `dbsistRel`.`Niveles` (`idNivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Escolaridades_Personas1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `dbsistRel`.`Personas` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistRel`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistRel`.`Categorias` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistRel`.`Programas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistRel`.`Programas` (
  `idProgramas` INT NOT NULL AUTO_INCREMENT,
  `idCategoria` INT NOT NULL,
  `nombre` VARCHAR(255) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`idProgramas`),
  CONSTRAINT `fk_ProgramasSociales_Categorias1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `dbsistRel`.`Categorias` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistRel`.`Ingresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistRel`.`Ingresos` (
  `idIngreso` INT NOT NULL AUTO_INCREMENT,
  `cantidad` VARCHAR(45) NULL,
  `monto` INT NULL,
  `idProgramas` INT NOT NULL,
  `idPersona` INT NOT NULL,
  PRIMARY KEY (`idIngreso`),
  CONSTRAINT `fk_Ingresos_Programas1`
    FOREIGN KEY (`idProgramas`)
    REFERENCES `dbsistRel`.`Programas` (`idProgramas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingresos_Personas1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `dbsistRel`.`Personas` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistRel`.`situtacionHabitacionales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistRel`.`situtacionHabitacionales` (
  `idsitutacionHabitacionale` INT NOT NULL AUTO_INCREMENT,
  `tenecia` VARCHAR(45) NULL,
  `permisoOcupacion` TINYINT NULL,
  `tipoLote` VARCHAR(45) NULL,
  `idLote` INT NOT NULL,
  `idPersona` INT NOT NULL,
  PRIMARY KEY (`idsitutacionHabitacionale`),
  CONSTRAINT `fk_situtacionHabitacionales_Lotes1`
    FOREIGN KEY (`idLote`)
    REFERENCES `dbsistRel`.`Lotes` (`idLote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_situtacionHabitacionales_Personas1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `dbsistRel`.`Personas` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistRel`.`Construcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistRel`.`Construcciones` (
  `idConstruccion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`idConstruccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistRel`.`detalleConstrucciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistRel`.`detalleConstrucciones` (
  `iddetalleConstruccion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `estado` TINYINT NULL,
  `idConstruccion` INT NOT NULL,
  PRIMARY KEY (`iddetalleConstruccion`),
  CONSTRAINT `fk_detalleConstrucciones_tipoConstrucciones1`
    FOREIGN KEY (`idConstruccion`)
    REFERENCES `dbsistRel`.`Construcciones` (`idConstruccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistRel`.`DetalleCasa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistRel`.`DetalleCasa` (
  `idDetalleCasa` INT NOT NULL AUTO_INCREMENT,
  `idCasa` INT NOT NULL,
  `tipoVivienda` TINYINT NULL,
  `hacinamiento` TINYINT NULL,
  `numeroHabitacion` INT NULL,
  PRIMARY KEY (`idDetalleCasa`),
  CONSTRAINT `fk_Habitaciones_Casas1`
    FOREIGN KEY (`idCasa`)
    REFERENCES `dbsistRel`.`Casas` (`idCasa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistRel`.`Habitaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistRel`.`Habitaciones` (
  `idHabitacion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idHabitacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistRel`.`InstitucionMedicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistRel`.`InstitucionMedicas` (
  `idInstitucionMedica` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `idCategoria` INT NOT NULL,
  PRIMARY KEY (`idInstitucionMedica`),
  CONSTRAINT `fk_InstitucionMedicas_Categorias1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `dbsistRel`.`Categorias` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistRel`.`MovimientoSociales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistRel`.`MovimientoSociales` (
  `idMovimientoSocial` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idMovimientoSocial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistRel`.`Movimientoxpersonas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistRel`.`Movimientoxpersonas` (
  `idMovimientoxperson` INT NOT NULL AUTO_INCREMENT,
  `idMovimientoSocial` INT NOT NULL,
  `idPersona` INT NOT NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`idMovimientoxperson`),
  CONSTRAINT `fk_Movimientoxpersonas_MovimientoSociales1`
    FOREIGN KEY (`idMovimientoSocial`)
    REFERENCES `dbsistRel`.`MovimientoSociales` (`idMovimientoSocial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movimientoxpersonas_Personas1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `dbsistRel`.`Personas` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistRel`.`DetalleHabitaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistRel`.`DetalleHabitaciones` (
  `idDetalleHabitacion` INT NOT NULL AUTO_INCREMENT,
  `idHabitacion` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`idDetalleHabitacion`),
  CONSTRAINT `fk_DetalleHabitaciones_Habitaciones1`
    FOREIGN KEY (`idHabitacion`)
    REFERENCES `dbsistRel`.`Habitaciones` (`idHabitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistRel`.`CasaHabitaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistRel`.`CasaHabitaciones` (
  `idCasaHabitacion` INT NOT NULL AUTO_INCREMENT,
  `idCasa` INT NOT NULL,
  `idDetalleHabitacion` INT NOT NULL,
  PRIMARY KEY (`idCasaHabitacion`),
  CONSTRAINT `fk_CasaHabitaciones_Casas1`
    FOREIGN KEY (`idCasa`)
    REFERENCES `dbsistRel`.`Casas` (`idCasa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CasaHabitaciones_DetalleHabitaciones1`
    FOREIGN KEY (`idDetalleHabitacion`)
    REFERENCES `dbsistRel`.`DetalleHabitaciones` (`idDetalleHabitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbsistRel`.`CasasDetalleConstrucciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbsistRel`.`CasasDetalleConstrucciones` (
  `idCasaDetalleConstruccion` INT NULL AUTO_INCREMENT,
  `idCasa` INT NOT NULL,
  `iddetalleConstruccion` INT NOT NULL,
  PRIMARY KEY (`idCasaDetalleConstruccion`),
  CONSTRAINT `fk_CasasDetalleConstrucciones_Casas1`
    FOREIGN KEY (`idCasa`)
    REFERENCES `dbsistRel`.`Casas` (`idCasa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CasasDetalleConstrucciones_detalleConstrucciones1`
    FOREIGN KEY (`iddetalleConstruccion`)
    REFERENCES `dbsistRel`.`detalleConstrucciones` (`iddetalleConstruccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
